// This file is generated by generate-info.py. Do not edit this file directly. */
import type { StaticImageData } from 'next/image';
import Image0 from "./59/01/image 1.png";
import Image1 from "./59/01/image.png";
import Image2 from "./59/01/thumbnail.png";
import Image3 from "./59/04/image 1.png";
import Image4 from "./59/04/image.png";
import Image5 from "./59/04/thumbnail.png";
import Image6 from "./59/05/image 1.png";
import Image7 from "./59/05/image 2.png";
import Image8 from "./59/05/image 3.png";
import Image9 from "./59/05/image.png";
import Image10 from "./59/05/thumbnail.png";
import Image11 from "./59/06/image.png";
import Image12 from "./59/06/thumbnail.png";
import Image13 from "./59/07/image 1.png";
import Image14 from "./59/07/image.png";
import Image15 from "./59/07/thumbnail.png";
import Image16 from "./59/08/image 1.png";
import Image17 from "./59/08/image 2.png";
import Image18 from "./59/08/image.png";
import Image19 from "./59/08/thumbnail.png";
import Image20 from "./59/09/image 1.png";
import Image21 from "./59/09/image 2.png";
import Image22 from "./59/09/image 3.png";
import Image23 from "./59/09/image 4.png";
import Image24 from "./59/09/image 5.png";
import Image25 from "./59/09/image 6.png";
import Image26 from "./59/09/image 7.png";
import Image27 from "./59/09/image 8.png";
import Image28 from "./59/09/image.png";
import Image29 from "./59/09/thumbnail.png";
import Image30 from "./59/14/image 1.png";
import Image31 from "./59/14/image 2.png";
import Image32 from "./59/14/image.png";
import Image33 from "./59/14/thumbnail.png";
import Image34 from "./59/15/image 1.png";
import Image35 from "./59/15/image 10.png";
import Image36 from "./59/15/image 11.png";
import Image37 from "./59/15/image 12.png";
import Image38 from "./59/15/image 13.png";
import Image39 from "./59/15/image 14.png";
import Image40 from "./59/15/image 15.png";
import Image41 from "./59/15/image 16.png";
import Image42 from "./59/15/image 17.png";
import Image43 from "./59/15/image 18.png";
import Image44 from "./59/15/image 19.png";
import Image45 from "./59/15/image 2.png";
import Image46 from "./59/15/image 20.png";
import Image47 from "./59/15/image 21.png";
import Image48 from "./59/15/image 22.png";
import Image49 from "./59/15/image 23.png";
import Image50 from "./59/15/image 24.png";
import Image51 from "./59/15/image 25.png";
import Image52 from "./59/15/image 26.png";
import Image53 from "./59/15/image 27.png";
import Image54 from "./59/15/image 28.png";
import Image55 from "./59/15/image 29.png";
import Image56 from "./59/15/image 3.png";
import Image57 from "./59/15/image 30.png";
import Image58 from "./59/15/image 31.png";
import Image59 from "./59/15/image 32.png";
import Image60 from "./59/15/image 33.png";
import Image61 from "./59/15/image 34.png";
import Image62 from "./59/15/image 4.png";
import Image63 from "./59/15/image 5.png";
import Image64 from "./59/15/image 6.png";
import Image65 from "./59/15/image 7.png";
import Image66 from "./59/15/image 8.png";
import Image67 from "./59/15/image 9.png";
import Image68 from "./59/15/image.png";
import Image69 from "./59/15/thumbnail.png";
import Image70 from "./60/03/image 1.png";
import Image71 from "./60/03/image 2.png";
import Image72 from "./60/03/image 3.png";
import Image73 from "./60/03/image.png";
import Image74 from "./60/03/thumbnail.png";
import Image75 from "./60/04/image 1.png";
import Image76 from "./60/04/image.png";
import Image77 from "./60/04/thumbnail.png";
import Image78 from "./60/05/image.png";
import Image79 from "./60/05/thumbnail.png";
import Image80 from "./60/09/image 1.png";
import Image81 from "./60/09/image.png";
import Image82 from "./60/09/thumbnail.png";
import Image83 from "./60/10/image.png";
import Image84 from "./60/10/thumbnail.png";
import Image85 from "./60/11/image 1.png";
import Image86 from "./60/11/image.png";
import Image87 from "./60/11/thumbnail.png";
export const blogImages: { [key: string]: StaticImageData } = {
    "59/01/image 1.png": Image0,
    "59/01/image.png": Image1,
    "59/01/thumbnail.png": Image2,
    "59/04/image 1.png": Image3,
    "59/04/image.png": Image4,
    "59/04/thumbnail.png": Image5,
    "59/05/image 1.png": Image6,
    "59/05/image 2.png": Image7,
    "59/05/image 3.png": Image8,
    "59/05/image.png": Image9,
    "59/05/thumbnail.png": Image10,
    "59/06/image.png": Image11,
    "59/06/thumbnail.png": Image12,
    "59/07/image 1.png": Image13,
    "59/07/image.png": Image14,
    "59/07/thumbnail.png": Image15,
    "59/08/image 1.png": Image16,
    "59/08/image 2.png": Image17,
    "59/08/image.png": Image18,
    "59/08/thumbnail.png": Image19,
    "59/09/image 1.png": Image20,
    "59/09/image 2.png": Image21,
    "59/09/image 3.png": Image22,
    "59/09/image 4.png": Image23,
    "59/09/image 5.png": Image24,
    "59/09/image 6.png": Image25,
    "59/09/image 7.png": Image26,
    "59/09/image 8.png": Image27,
    "59/09/image.png": Image28,
    "59/09/thumbnail.png": Image29,
    "59/14/image 1.png": Image30,
    "59/14/image 2.png": Image31,
    "59/14/image.png": Image32,
    "59/14/thumbnail.png": Image33,
    "59/15/image 1.png": Image34,
    "59/15/image 10.png": Image35,
    "59/15/image 11.png": Image36,
    "59/15/image 12.png": Image37,
    "59/15/image 13.png": Image38,
    "59/15/image 14.png": Image39,
    "59/15/image 15.png": Image40,
    "59/15/image 16.png": Image41,
    "59/15/image 17.png": Image42,
    "59/15/image 18.png": Image43,
    "59/15/image 19.png": Image44,
    "59/15/image 2.png": Image45,
    "59/15/image 20.png": Image46,
    "59/15/image 21.png": Image47,
    "59/15/image 22.png": Image48,
    "59/15/image 23.png": Image49,
    "59/15/image 24.png": Image50,
    "59/15/image 25.png": Image51,
    "59/15/image 26.png": Image52,
    "59/15/image 27.png": Image53,
    "59/15/image 28.png": Image54,
    "59/15/image 29.png": Image55,
    "59/15/image 3.png": Image56,
    "59/15/image 30.png": Image57,
    "59/15/image 31.png": Image58,
    "59/15/image 32.png": Image59,
    "59/15/image 33.png": Image60,
    "59/15/image 34.png": Image61,
    "59/15/image 4.png": Image62,
    "59/15/image 5.png": Image63,
    "59/15/image 6.png": Image64,
    "59/15/image 7.png": Image65,
    "59/15/image 8.png": Image66,
    "59/15/image 9.png": Image67,
    "59/15/image.png": Image68,
    "59/15/thumbnail.png": Image69,
    "60/03/image 1.png": Image70,
    "60/03/image 2.png": Image71,
    "60/03/image 3.png": Image72,
    "60/03/image.png": Image73,
    "60/03/thumbnail.png": Image74,
    "60/04/image 1.png": Image75,
    "60/04/image.png": Image76,
    "60/04/thumbnail.png": Image77,
    "60/05/image.png": Image78,
    "60/05/thumbnail.png": Image79,
    "60/09/image 1.png": Image80,
    "60/09/image.png": Image81,
    "60/09/thumbnail.png": Image82,
    "60/10/image.png": Image83,
    "60/10/thumbnail.png": Image84,
    "60/11/image 1.png": Image85,
    "60/11/image.png": Image86,
    "60/11/thumbnail.png": Image87,
};
export const blogPaths: string[] = [
    "59/01",
    "59/04",
    "59/05",
    "59/06",
    "59/07",
    "59/08",
    "59/09",
    "59/14",
    "59/15",
    "60/03",
    "60/04",
    "60/05",
    "60/09",
    "60/10",
    "60/11",
];
export const blogMetadata: {
    [key: string]: {
        title: string;
        date: string;
        author: string;
        topic: string;
        thumbnail: StaticImageData;
        description: string;
    };
} = {
    "59/01": {
        title: `ロゴデザインの裏側に密着？！`,
        date: `2023.06.05`,
        author: `パート員 S.Y.`,
        topic: `PRパート`,
        thumbnail: blogImages["59/01/thumbnail.png"],
        description: `菁々祭の顔、と聞いてロゴを思い浮かべる人も多いのではないでしょうか？ そんな菁々祭のロゴは、なんと生徒によって作られているのです！毎年クオリティが高くてすごいですよね。今回はなんと第 58 回菁々祭と第 59 回菁々祭のロゴデザインを手掛けた製作セクション長にお話を聞いてきました。`,
    },
    "59/04": {
        title: `お化け屋敷の正体を直撃インタビュー！`,
        date: `2023.06.05`,
        author: `PR パート員 M.K.`,
        topic: `お化け屋敷セクション`,
        thumbnail: blogImages["59/04/thumbnail.png"],
        description: `菁々祭の中でも特に内容が秘匿されたブース、お化け屋敷。今回の取材では、校舎の片隅で暗幕に包まれた実情、さらにはそのまとめ役について、前回と今回のトップであるお化け屋敷セクション長に話を伺いました。`,
    },
    "59/05": {
        title: `Webサイトができるまで...【技術＆製作セクション長インタビュー】`,
        date: `2023.06.05`,
        author: `PRパート長`,
        topic: `技術・製作セクション`,
        thumbnail: blogImages["59/05/thumbnail.png"],
        description: `ついに公開された第 59 回菁々祭公式 Web サイト。そんな Web サイト制作を担当した PR パート技術セクション長と製作セクション長のお二人にお話を伺いました。`,
    },
    "59/06": {
        title: `折り紙研究部の巨大作品に迫る`,
        date: `2023.06.26`,
        author: `PRパート員K.K.`,
        topic: `折り紙研究部`,
        thumbnail: blogImages["59/06/thumbnail.png"],
        description: `皆さんは東大寺の文化祭で最も印象的なものは何ですか？お化け屋敷だったり、転心殿前で行われる和太鼓だったりが思い浮かぶのではないでしょうか？今回はその中でも折り紙研究部の巨大作品に迫ります。そして巨大作品を展示している折り紙研究部の部長にお話を伺いました。`,
    },
    "59/07": {
        title: `菁々祭との出会い`,
        date: `2023.06.26`,
        author: `PRパート副パート長`,
        topic: `紹介`,
        thumbnail: blogImages["59/07/thumbnail.png"],
        description: `長年東大寺学園の一大イベントとして代々受け継がれてきた菁々祭。この記事ではぼくが小 5 の時に初めて遊びに行って衝撃を受けた第５４回菁々祭「fortissimo」を現在の菁々祭と比較しながら振り返っていきます。`,
    },
    "59/08": {
        title: `菁々祭を支える者達～パート・セクション紹介～`,
        date: `2023.06.26`,
        author: `PRパート員I.R.`,
        topic: `紹介`,
        thumbnail: blogImages["59/08/thumbnail.png"],
        description: `毎年盛大に行われる菁々祭。菁々祭の運営は、多くの生徒たちによって支えられており、その業務はパートによって分担されて行われます。ここでは、パートやその下部組織であるセクションについて、紹介していきます。`,
    },
    "59/09": {
        title: `【ギャラリー】ロゴモニュメント「四季彩」の記録`,
        date: `2023.06.26`,
        author: `PRパート副パート長`,
        topic: `ロゴモニュメントセクション`,
        thumbnail: blogImages["59/09/thumbnail.png"],
        description: `「門」と共に菁々祭を飾るために佇むロゴモニュメント。前回の「四季彩」のロゴモニュメントの製作にちょっぴりかかわった身として、その製作過程の一部をここに残しておきます。`,
    },
    "59/14": {
        title: `音楽部と室内楽部のコラボ?!合同バンドのメンバーに聞く`,
        date: `2023.08.25`,
        author: `PRパート員 K.N`,
        topic: `音楽部・室内楽部`,
        thumbnail: blogImages["59/14/thumbnail.png"],
        description: `今年は音楽部と室内楽部の合同バンドがライブをするようです。あまり接点がないように思える 2 つのクラブが集まるこの企画は、一体どのようなものなのでしょうか？企画者である音楽部員のドラム担当の O さんとバンドのメンバーである室内楽部員のトランペット担当の K さんにお話を伺いました。`,
    },
    "59/15": {
        title: `菁々祭パンフレット編集後記`,
        date: `2023.10.08`,
        author: `文化祭実行委員長`,
        topic: `製作セクション`,
        thumbnail: blogImages["59/15/thumbnail.png"],
        description: `より便利に菁々祭を楽しむために欠かせないパンフレット。展示やイベントなど幅広く菁々祭の情報を網羅するパンフレットはどのようにしてうまれるのでしょうか。パンフレットを「作る」という視点から覗いてみませんか？未公開の裏話も続々…`,
    },
    "60/03": {
        title: `作者的文化祭のあるきかた`,
        date: `2024.09.05`,
        author: `PRパート員 S.K.`,
        topic: `製作セクション`,
        thumbnail: blogImages["60/03/thumbnail.png"],
        description: `この記事では「せっかく菁々祭に来たのにどこを回ればいいのかわからない」「回りたい場所があったのに混んでて全然楽しめなかった」といったあるあるを解消すべく、同好会の展示を知り尽くしている（はずの）僕がおすすめの回るルートや展示を紹介していきます！`,
    },
    "60/04": {
        title: `テーマ・ロゴ発表映像のあれこれ`,
        date: `2024.09.05`,
        author: `PRパート員 S.Y.`,
        topic: `製作セクション`,
        thumbnail: blogImages["60/04/thumbnail.png"],
        description: `今や菁々祭に火を点けるビッグイベントとなったテーマ・ロゴ発表。今年も例年以上に大きな反響を得ました。今回はそんなレベルの高い動画を出し続ける動画制作陣に話を伺います。\n\nテーマ・ロゴ発表映像はこちらから→\n\n[https://youtu.be/4h_s7_eRCo0](https://youtu.be/4h_s7_eRCo0)`,
    },
    "60/05": {
        title: `復活した書道パフォーマンス!!`,
        date: `2024.08.22`,
        author: `パート員 S.Y.`,
        topic: `PRパート`,
        thumbnail: blogImages["60/05/thumbnail.png"],
        description: `今年の菁々祭では書道部がパフォーマンスを行います。そのパフォーマンスについて書道部の部長にお話を伺いました。`,
    },
    "60/09": {
        title: `全国強豪のクイズ研究部、今年5年ぶりの〇〇〇〇を開催？！`,
        date: `2024.08.22`,
        author: `PRパート員 M.K.`,
        topic: `クイズ研究部`,
        thumbnail: blogImages["60/09/thumbnail.png"],
        description: `昨年、「高校生クイズ」や「東大王」で優勝した強豪・クイズ研究部。このブログではそんなクイズ研究部の見どころや実に 5 年ぶりの開催となる〇〇〇〇について、今回副部長に独占取材！ 徹底的にその実態を解剖します！！`,
    },
    "60/10": {
        title: `文化祭の裏側、会計パートの仕事に迫る！！`,
        date: `2024.08.22`,
        author: `PRパート員 A.Y. & Y.U. & R.N.`,
        topic: `会計パート`,
        thumbnail: blogImages["60/10/thumbnail.png"],
        description: `この大規模なイベント、菁々祭の予算折衝など重役を担う会計パート。本ブログではそんな会計パートについてどんな団体がどのように仕事をこなしているのか、会計パート長に協力してもらいながら紹介していこうと思います。`,
    },
    "60/11": {
        title: `お化け屋敷の裏側を暴く！？`,
        date: `2024.09.05`,
        author: `PRパート員 S.K.`,
        topic: `製作セクション`,
        thumbnail: blogImages["60/11/thumbnail.png"],
        description: `この記事では「せっかく菁々祭に来たのにどこを回ればいいのかわからない」「回りたい場所があったのに混んでて全然楽しめなかった」といったあるあるを解消すべく、同好会の展示を知り尽くしている（はずの）僕がおすすめの回るルートや展示を紹介していきます！`,
    },
};
