// This file is generated by generate-info.py. Do not edit this file directly. */
import type { StaticImageData } from 'next/image';
import Image0 from "./59/04/image 1.png";
import Image1 from "./59/04/image.png";
import Image2 from "./59/04/thumbnail.png";
import Image3 from "./59/05/image 1.png";
import Image4 from "./59/05/image 2.png";
import Image5 from "./59/05/image 3.png";
import Image6 from "./59/05/image.png";
import Image7 from "./59/05/thumbnail.png";
import Image8 from "./60/04/image 1.png";
import Image9 from "./60/04/image.png";
import Image10 from "./60/04/thumbnail.png";
import Image11 from "./60/09/image 1.png";
import Image12 from "./60/09/image.png";
import Image13 from "./60/09/thumbnail.png";
import Image14 from "./60/10/image.png";
import Image15 from "./60/10/thumbnail.png";
export const blogImages: { [key: string]: StaticImageData } = {
    "59/04/image 1.png": Image0,
    "59/04/image.png": Image1,
    "59/04/thumbnail.png": Image2,
    "59/05/image 1.png": Image3,
    "59/05/image 2.png": Image4,
    "59/05/image 3.png": Image5,
    "59/05/image.png": Image6,
    "59/05/thumbnail.png": Image7,
    "60/04/image 1.png": Image8,
    "60/04/image.png": Image9,
    "60/04/thumbnail.png": Image10,
    "60/09/image 1.png": Image11,
    "60/09/image.png": Image12,
    "60/09/thumbnail.png": Image13,
    "60/10/image.png": Image14,
    "60/10/thumbnail.png": Image15,
};
export const blogPaths: string[] = [
    "59/04",
    "59/05",
    "60/04",
    "60/09",
    "60/10",
];
