import glob
import os

os.chdir(os.path.dirname(__file__))
with open("blog-info.ts", "w") as f:
    f.write("// This file is generated by generate-info.py. Do not edit this file directly. */\n")
    f.write("import type { StaticImageData } from 'next/image';\n")
    paths = glob.glob("./**/*.png", recursive=True)
    paths = [path.replace("\\", "/") for path in paths]
    paths.sort()
    for i, path in enumerate(paths):
        f.write(f'import Image{i} from "{path}";\n')
    f.write("export const blogImages: { [key: string]: StaticImageData } = {\n")
    for i, path in enumerate(paths):
        f.write(f'    "{path[2:]}": Image{i},\n')
    f.write("};\n")
    f.write("export const blogPaths: string[] = [\n")
    for rd in os.listdir("./"):
        if not os.path.isdir(rd):
            continue
        for idx in os.listdir("./" + rd):
            f.write(f'    "{rd}/{idx}",\n')
    f.write("];\n")
